# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapshotPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'iOSSnapshotTestCase'

  # Pods for SnapshotPOC

  target 'SnapshotPOCTests' do
    inherit! :search_paths
    pod 'iOSSnapshotTestCase'
  end

  target 'SnapshotPOCUITests' do
     pod 'iOSSnapshotTestCase'
  end
end
